FROM ubuntu:bionic AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
      python3 python3-dev python3-pip python3-setuptools python3-wheel \
      build-essential patchelf zlib1g-dev \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install nuitka zstandard

WORKDIR /app
COPY . .

RUN nuitka \
    --standalone \
    --onefile \
    --output-dir=/app/dist \
    --output-filename=mypkg \
    main.py

# # final stage to just hold the binary
# FROM ubuntu:bionic
# COPY --from=builder /app/dist/mypkg /usr/local/bin/mypkg
# CMD ["mypkg"]
