Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_version = "20241002.0.0"
  config.vm.hostname = "ubuntu-jammy64"
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", ip: "192.168.56.16"
  config.vm.network :forwarded_port, guest: 22, host: 2501, id: "ssh"

  config.ssh.insert_key = false

  config.vm.provision "shell" do |s|
    ssh_pub_key_path = File.expand_path("~/.ssh/dev.pub")
    ssh_pub_key = File.read(ssh_pub_key_path).strip

    s.inline = <<-SHELL
      echo "#{ssh_pub_key}" >> /home/vagrant/.ssh/authorized_keys
      echo "#{ssh_pub_key}" >> /root/.ssh/authorized_keys

      _apt_file=/etc/apt/apt.conf.d/70debconf
      [ -f "$_apt_file" ] && sudo rm -v $_apt_file
      sudo dpkg-reconfigure debconf -f noninteractive -p critical
      sudo dpkg --configure -a

      # sudo apt-get update
      sudo apt-get install -y --no-install-recommends vim ca-certificates wget zip unzip python3
    SHELL
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 2
    vb.memory = 2048
    vb.check_guest_additions = false
  end
end
