[PHP]
memory_limit = 512M
max_execution_time = 600
upload_max_filesize = 60M
post_max_size = 60M
; listen = 0.0.0.0:9000
; listen.acl_users = "apache,nginx"
; listen.acl_groups = "apache,nginx"

[Date]
date.timezone = Asia/Dubai
