FROM node:18.18.0-slim AS base

WORKDIR /_base
COPY package*.json .
RUN npm install --omit=dev

FROM node:18.18.0-slim AS builder

WORKDIR /_build
COPY package*.json .
RUN npm install

COPY ./tsconfig.json .
COPY ./src ./src
RUN npm run build

FROM node:18.18.0-slim

WORKDIR /app
COPY --from=base /_base/node_modules ./node_modules
COPY --from=builder /_build/package*.json .
COPY --from=builder /_build/dist ./dist

CMD ["npm", "start"]
