FROM node:18.18.0-slim AS builder

WORKDIR /_build
COPY package*.json .
RUN npm install

COPY . .
RUN npm run build

FROM nginx:1.27.1-alpine
COPY --from=builder /_build/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
